const darkColor = '#2D5D83';

export default {
  black: '#000',
  blue: '#2D5D83',
  lightblue: '#13F5FF',
  red: 'red',
  light: '#F6F4F4',
  grey: '#CBCECE',
  lightgrey: '#eee',
  stronggrey: '#777E7E',
  green: '#04F6A3',
  stronggreen: '#15BE31',

  darkColor,
  lightColor: '#F6F4F4',
  mainColor: '#0ea7bb',
  disabledColor: '#C4C6C6',
  selectedColor: darkColor,
  textColorDefault: '#5A5B5C',
  archiveButton: '#34B459',
  progressBar: '#04F6A3',
  statGreenColor: '#0BA849',
  position: '#F53434',
  destination: '#707070',
  route: '#05CA5A',

  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: darkColor,
  noticeText: '#fff',

  transportButton: '#36C3D9',
  serviceDomicileButton: '#DB771F',
  santeButton: '#6BB119',
  informatiqueButton: '#0EB39D',
  surveillanceButton: '#D053F6',
  autoButton: '#B8A60B',
};
